services:
  mongodb:
    image: mongo
    container_name: mongo_db3
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ameda
  mongo-express:
    image: mongo-express
    container_name: mongo_express5
    restart: always
    ports:
      - 7979:7979
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ameda
      - ME_CONFIG_MONGODB_SERVER=mongodb2
volumes:
  mongo: {}